### ISSUE TITLE
Zombie Escape Disappears?

### ISSUE THREAD

**Issue by slcns11212** [RisottoMan/AutoEvent#101]
Was Zombie Escape removed? I didn't find it and I wanted to rejoin the zombie escape into my game what to do

**Comment by RisottoMan** [comment]
I deleted this mini-game because no one played it, it had a lot of bugs and no one talked about it. Fixing bugs took me a lot of time. So I decided to remove the mini-game. If you want to restore the mini-game, then copy the code and use the loader of custom mini-games to launch them.

If you want to create a FNAF mini-game or want to do support, then write to me at discord.

**Comment by slcns11212** [comment]
ok,thanks
